### ISSUE TITLE
Enable targeted-context aware shortcuts

### ISSUE THREAD

**Issue by nandenjin** [mkobayashime/video-stream-shortcuts#1]
## Problem

The extension seems to be catching events even I typing texts on player page. I noticed when I editing captions for my video on MS Stream.

## How to solve

Detect the targeting (focusing) element ([`document.activeElement`](https://developer.mozilla.org/ja/docs/Web/API/Document/activeElement)?) and disable shortcuts when it is something editable by keyboards.

**Comment by mkobayashime** [comment]
Thanks a lot for the suggestion.
I'll work on it.

**Comment by mkobayashime** [comment]
@nandenjin ba9494d shoud have fixed this.

**Comment by mkobayashime** [comment]
@nandenjin Released as v2.1 in Chrome Web Store!
